<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="7" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-06T16:08:07 IST" name="Default suite" finished-at="2023-10-06T16:08:08 IST" duration-ms="1379">
    <groups>
    </groups>
    <test started-at="2023-10-06T16:08:07 IST" name="Default test" finished-at="2023-10-06T16:08:08 IST" duration-ms="1379">
      <class name="org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging">
        <test-method is-config="true" signature="restrictionPage()[pri:0, instance:org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging@7c729a55]" started-at="2023-10-06T16:07:49 IST" name="restrictionPage" finished-at="2023-10-06T16:08:07 IST" duration-ms="17386" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- restrictionPage -->
        <test-method signature="step_1_Confirm_Eligibility()[pri:1, instance:org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging@7c729a55]" started-at="2023-10-06T16:08:07 IST" name="step_1_Confirm_Eligibility" finished-at="2023-10-06T16:08:07 IST" duration-ms="371" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step_1_Confirm_Eligibility -->
        <test-method signature="step_2_Create_Your_Account(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:2, instance:org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging@7c729a55]" started-at="2023-10-06T16:08:07 IST" name="step_2_Create_Your_Account" data-provider="TestData" finished-at="2023-10-06T16:08:08 IST" duration-ms="894" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging.step_2_Create_Your_Account(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException,java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: step_2_Create_Your_Account([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [null,null,null,null,null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging.step_2_Create_Your_Account(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException,java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: step_2_Create_Your_Account([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [null,null,null,null,null]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step_2_Create_Your_Account -->
        <test-method signature="mobileNumberVerification(java.lang.String)[pri:3, instance:org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging@7c729a55]" started-at="2023-10-06T16:08:08 IST" name="mobileNumberVerification" data-provider="TestData" finished-at="2023-10-06T16:08:08 IST" duration-ms="56" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging.mobileNumberVerification(java.lang.String) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: mobileNumberVerification([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [null,null,null,null,null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging.mobileNumberVerification(java.lang.String) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: mobileNumberVerification([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [null,null,null,null,null]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mobileNumberVerification -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging@7c729a55]" started-at="2023-10-06T16:08:08 IST" name="closeBrowser" finished-at="2023-10-06T16:08:09 IST" duration-ms="584" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
