<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Akshay-PC" failures="0" tests="7" name="org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging" time="1.321" errors="2" timestamp="2023-10-06T16:08:09 IST" skipped="4">
  <testcase classname="org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging" name="step_1_Confirm_Eligibility" time="0.371"/>
  <system-out/>
  <testcase classname="org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging" name="step_2_Create_Your_Account" time="0.894">
    <error message="
[public void org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging.step_2_Create_Your_Account(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException,java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: step_2_Create_Your_Account([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [null,null,null,null,null]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging.step_2_Create_Your_Account(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException,java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: step_2_Create_Your_Account([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [null,null,null,null,null]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- step_2_Create_Your_Account -->
  <system-out/>
  <testcase classname="org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging" name="mobileNumberVerification" time="0.056">
    <error message="
[public void org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging.mobileNumberVerification(java.lang.String) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: mobileNumberVerification([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [null,null,null,null,null]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging.mobileNumberVerification(java.lang.String) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: mobileNumberVerification([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [null,null,null,null,null]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- mobileNumberVerification -->
  <system-out/>
  <testcase classname="org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging" name="step_3_Basic_Data">
    <skipped/>
  </testcase> <!-- step_3_Basic_Data -->
  <system-out/>
  <testcase classname="org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging" name="Step_4_Work_Experience">
    <skipped/>
  </testcase> <!-- Step_4_Work_Experience -->
  <system-out/>
  <testcase classname="org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging" name="Step_5_Annual_Compensation">
    <skipped/>
  </testcase> <!-- Step_5_Annual_Compensation -->
  <system-out/>
  <testcase classname="org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging" name="Step_5_Education">
    <skipped/>
  </testcase> <!-- Step_5_Education -->
  <system-out/>
</testsuite> <!-- org.fxb.experts_staging.testcases.TC_For_Registration_Experts_Staging -->
